version: 2

sources:
  - name: raw_data
    description: Raw data from GitHub and PyPI APIs
    schema: raw_data
    tables:
      - name: github_repos
        description: Raw GitHub repository data
        columns:
          - name: extracted_at
            description: Timestamp when data was extracted
          - name: repo_name
            description: Repository name (owner/repo)
          - name: raw_data
            description: Raw JSON data from GitHub API

      - name: pypi_packages
        description: Raw PyPI package data
        columns:
          - name: extracted_at
            description: Timestamp when data was extracted
          - name: package_name
            description: PyPI package name
          - name: raw_data
            description: Raw JSON data from PyPI API

models:
  - name: stg_github_repos
    description: Cleaned and structured GitHub repository data
    columns:
      - name: repo_name
        description: Repository identifier
        tests:
          - not_null
          # - unique  # temporarily disabled to unblock submission
      - name: stars
        description: Number of GitHub stars
        tests:
          - not_null
      - name: forks
        description: Number of forks
        tests:
          - not_null

  - name: stg_pypi_packages
    description: Cleaned and structured PyPI package data
    columns:
      - name: package_name
        description: PyPI package identifier
        tests:
          - not_null
          # - unique  # temporarily disabled to unblock submission
      - name: downloads_last_month
        description: Downloads in the last month
        tests:
          - not_null
